[mypy]
python_version = 3.12
plugins =
  sqlalchemy.ext.mypy.plugin,
  pydantic.mypy
mypy_path = src
namespace_packages = True
explicit_package_bases = True

disallow_untyped_defs = true
disallow_incomplete_defs = true

disallow_any_unimported = true
# disallow_any_expr = true
# disallow_any_decorated = true
# disallow_any_generics = true
disallow_subclassing_any = true

warn_return_any = true
warn_unused_ignores = true
strict_optional = true

[mypy-tests.*]
disable_error_code =
  call-arg

[mypy-src.infrastructure.database.models.*]
disable_error_code =
  name-defined